- name: Provision Raspberry Pi
  hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Ansible requirements
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - aptitude

  roles:
    - upgrade
    - common
    - ssh
    - avahi
    - homebridge
