- name: Set authorized key
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', public_key) }}"

- name: Change default password
  user:
    name: "{{ user }}"
    password: "{{ password }}"

- name: Disallow password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^[# ]*PasswordAuthentication "
    line: "PasswordAuthentication no"
  notify: restart ssh

- name: Disallow root SSH access
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^[# ]*PermitRootLogin "
    line: "PermitRootLogin no"
  notify: restart ssh
