- name: Set authorized key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', item) }}"
  with_items: "{{ ssh_authorized_keys }}"

- name: Disallow password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^[# ]*PasswordAuthentication "
    line: "PasswordAuthentication no"
  notify: restart ssh

- name: Disallow root SSH access
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^[# ]*PermitRootLogin "
    line: "PermitRootLogin no"
  notify: restart ssh
