- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libavahi-compat-libdnssd-dev

- name: Install homebridge and homebridge-miio
  npm:
    name: homebridge
    global: yes
    state: latest

- name: Install homebridge plugins
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items:
    - homebridge-miio

- name: Create homebridge group
  group:
    name: "{{ homebridge_service_group }}"

- name: Create homebridge user
  user:
    name: "{{ homebridge_service_user }}"
    group: "{{ homebridge_service_group }}"
    createhome: no

- name: Create data directory
  file:
    path: "{{ homebridge_service_data_directory }}"
    state: directory
    owner: "{{ homebridge_service_user }}"
    group: "{{ homebridge_service_group }}"
    mode: u=rwx,g=rx,o=rx

- name: Configure
  template:
    src: config.json.j2
    dest: "{{ homebridge_service_data_directory }}/config.json"
    owner: "{{ homebridge_service_user }}"
    group: "{{ homebridge_service_group }}"
    mode: u=rw,g=r,o=r
  notify: restart homebridge

- name: Detect homebridge executable
  command: which homebridge
  changed_when: no
  register: which_homebridge

- name: Define homebridge executable
  set_fact:
    homebridge_executable: "{{ which_homebridge.stdout|trim }}"

- name: Configure autostart
  template:
    src: "{{ item.key }}"
    dest: "{{ item.value }}"
  with_dict:
    homebridge.j2: /etc/default/homebridge
    homebridge.service.j2: /etc/systemd/system/homebridge.service

- name: Enable autostart
  systemd:
    name: homebridge.service
    daemon_reload: yes
    enabled: yes
    state: started
